import React from 'react';

export default function Terms() {
  return (
    <div className="bg-[#0A0A0A] w-full min-h-screen pb-24 text-slate-300 relative">
      <div className="relative pt-32 pb-12 overflow-hidden bg-[#0A0A0A] border-b border-white/5 z-10">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 relative z-10">
          <h1 className="text-4xl md:text-5xl font-extrabold text-white mb-6 tracking-tight">Terms of Service</h1>
          <p className="text-lg text-slate-400 font-medium">Effective Date: May 22, 2026</p>
        </div>
      </div>

      <div className="mx-auto max-w-4xl px-4 py-16 sm:px-6 lg:px-8 relative z-20">
        <div className="prose prose-invert prose-slate max-w-none prose-headings:text-white prose-a:text-blue-400">
          <h2>1. Agreement to Terms</h2>
          <p>
            By accessing or using the NonaCrypt platform, API, or related services (collectively, the "Services"), 
            you agree to be bound by these Terms of Service. If you are entering into these terms on behalf of an 
            entity, you represent that you have the authority to bind that entity.
          </p>

          <h2>2. Use of Services</h2>
          <p>
            We grant you a non-exclusive, non-transferable, revocable license to access and use our Services strictly 
            in accordance with your service tier and pricing plan.
          </p>

          <h2>3. Acceptable Use Policy</h2>
          <p>You agree not to use the Services to:</p>
          <ul>
            <li>Process highly classified government data without a customized secure envelope agreement.</li>
            <li>Reverse engineer, decompile, or attempt to extract the source code of our proprietary models.</li>
            <li>Generate malicious software or content intended to deceive or harm others.</li>
            <li>Exceed the rate limits defined in your enterprise SLA.</li>
          </ul>

          <h2>4. Intellectual Property</h2>
          <p>
            NonaCrypt retains all right, title, and interest in and to the Services, including all foundational models, 
            weights, architectures, API designs, and documentation. You retain all rights to your customer data and 
            the specific outputs generated by your authorized use.
          </p>
          
          <h2>5. Limitation of Liability</h2>
          <p>
            In no event shall NonaCrypt be liable for any indirect, incidental, special, consequential, or punitive damages,
            including without limitation, loss of profits, data, use, goodwill, or other intangible losses.
          </p>
        </div>
      </div>
    </div>
  );
}
